name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
      - '.github/workflows/*'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
      - '.github/workflows/*'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      solution-file-path: KerbalVR_Mod/KerbalVR_Mod.sln
      use-ckan: true
      artifacts: KerbalVR_Mod/GameData 'KerbalVR_Mod/Optional Mods' KerbalVR_Mod/KSP_x64_Data KerbalVR_Mod/vrinstaller.exe KerbalVR_Mod/KerbalVR-Dependencies.ckan README.md CHANGELOG.md
